[IO] Add Parquet Dataset Support.
alibaba/DeepRec pull request #270
Opened 2022-06-19 18:15 UTC by A-Wanderer

2022-06-24 10:25 UTC, 2sin18 requested changes

2022-06-24 10:25 UTC, 2sin18 commented on tensorflow/core/ops/parquet_ops.cc
> +REGISTER_OP("ParquetTabularDataset")
Please rename ops to prevent op name conflicts with HybridBackend

2022-06-24 10:25 UTC, 2sin18 commented on tensorflow/workspace.bzl
> +        sha256 = "a27971e2a71c412ae43d998b7b6d06201c7a3da382c804dcdc4a8126ccbabe67",
Attention: Arrow 4.x is incompatible with Apsara libraries. Compile DeepRec with Apsara should disable the capabilities.

2022-06-28 10:02 UTC, liutongxuan approved these changes

2022-06-28 10:03 UTC, liutongxuan commented on tensorflow/workspace.bzl
> +        sha256 = "a27971e2a71c412ae43d998b7b6d06201c7a3da382c804dcdc4a8126ccbabe67",
开源版本暂时不考虑飞天，咱们内部版本会有修改。

2022-06-29 01:41 UTC, 2sin18 commented on tensorflow/workspace.bzl
> +        sha256 = "a27971e2a71c412ae43d998b7b6d06201c7a3da382c804dcdc4a8126ccbabe67",
@A-Wanderer No, you should add a compiler macro to disable the library if DeepRec must be compiled with apsara libraries.

2022-06-29 01:46 UTC, 2sin18 approved these changes

2022-06-29 06:07 UTC, liutongxuan approved these changes

2022-06-30 02:42 UTC, liutongxuan approved these changes

2022-07-01 02:27 UTC, liutongxuan approved these changes

2022-07-01 11:26 UTC, liutongxuan approved these changes

2022-07-04 10:07 UTC, merged